### ISSUE TITLE
Commit 136149b breaks LED function on MMU controlled by Happy Hare

### ISSUE THREAD

**Issue by iamnotahippy** [KalicoCrew/kalico#485]
Since converting Kalico to a python package, SB LEDs continue to work, but LEDs on my MMU which are controlled by Happy Hare no longer function. Rolling back to commit b9a62e1 brings back function. 

You can find my discussion with the HH dev and logs in the Happy Hare issue 557

https://github.com/moggieuk/Happy-Hare/issues/557

**Comment by rogerlz** [comment]
Hi, 
I believe this has been fixed on HH side by @moggieuk (thank you).
We tested many 3rd party modules before merging the python package PR but we probably missed something.
